# Generated by Django 4.0.5 on 2022-07-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='senditapp.parcelstatus'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
