# Generated by Django 4.0.5 on 2022-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
