# Generated by Django 4.0.5 on 2022-07-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelstatus',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='parcelstatus',
            name='in_transit',
        ),
        migrations.RemoveField(
            model_name='parcelstatus',
            name='warehouse',
        ),
    ]
