# Generated by Django 4.0.5 on 2022-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0002_alter_parcel_parcel_status_alter_parcel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
