# Generated by Django 4.0.5 on 2022-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0002_remove_parcelstatus_arrived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['-pk']},
        ),
    ]
