# Generated by Django 4.0.5 on 2022-07-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0003_remove_admin_email_remove_admin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcel_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='senditapp.parcelstatus'),
        ),
    ]
