# Generated by Django 4.0.5 on 2022-07-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0003_alter_parcel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='parcel_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel', to='senditapp.parcelstatus'),
        ),
    ]
