# Generated by Django 4.0.5 on 2022-07-13 07:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senditapp', '0004_alter_parcel_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='parcel_pic'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
